version: "3.8"

services:
  app1:
    build:
      context: app
    image: node-app-82c6jauwh5
    container_name: app1
    restart: unless-stopped
    environment: 
      PORT: 3000
    networks: 
      - frontend
  
  app2:
    image: node-app-82c6jauwh5
    container_name: app2
    restart: unless-stopped
    environment: 
      PORT: 3001
    networks: 
      - frontend
  
  loadbalancer:
    depends_on:
      - app1
      - app2
    build:
      context: loadbalancer
    image: loadbalancer-82c6jauwh5
    container_name: loadbalancer
    restart: unless-stopped
    ports: 
      - '8080:80'
    networks:
      - frontend

networks: 
  frontend:
